stages:
  - build

variables:
  GIT_STRATEGY: clone
  GIT_SUBMODULE_STRATEGY: recursive
  RULES_CHANGES_PATH: "**/*"

build:contracts:
    stage: build
    image: public.ecr.aws/docker/library/node:18
    cache:
        paths:
            - node_modules/
    script:
        - npm i -g pnpm
        - pnpm install
        - pnpm hardhat compile
